### ISSUE TITLE
Base container v10.2 not properly evaluating bashio::config

### ISSUE THREAD

**Issue by dcmartin** [hassio-addons/addon-base#165]
# Problem/Motivation

My add-on buit with version 10.1 of the base container utilizes `bashio::config` to return the literal value for the configuration option, e.g. `timezone`, even when the configuration utilizes secrets, e.g. `timezone: '!secret ha-timezone'` which would return "America/Los_Angeles" or whatever the vaue of the secret.

In version 10.2 of the base container, the result is now the '!secret ha-timezone' string, not the value.

## Expected behavior

I expect to receive the literal value of the configuration option regardless of whether it is a secret or not.

## Actual behavior

Receive the string value of the unevaluated option (e.g. "!secret ha-timezone")

## Steps to reproduce

Use a secret as a configuration option and call `bashio::config`; experienced using version 0.10.145 of the Motion Classic add-on; reference line https://github.com/dcmartin/addon-motion-video0/blob/83d53e4203bfbb94b6890339b04e6c39da25f6ba/motion-video0/rootfs/usr/bin/motion.sh#L61

## Proposed changes

No change proposed.

**Comment by dcmartin** [comment]
I reset the build configuration for the add-on back to 10.1; built, pushed, updated on client (RaspberryPi3; HA 2021.11; supervised installation) from 0.10.145 (v10.2-based) to 0.10.146 (v10.1-based) and the problem no longer occurs.

**Comment by tjorim** [comment]
AFAIK, this is now handles by the supervisor instead of bashio for some time. I'll check later today.

**Comment by dcmartin** [comment]
@tjorim Can you provide alternative to `bashio::config` for add-on to receive processed secret as literal?  AFAIK that is/was the approved mechanism vs. using `jq` on the `options.json` file.

**Comment by frenck** [comment]
Stick with the 10.1 base image for now, is the best route at this point. At least it has been looked into

**Comment by frenck** [comment]
Fixed with the release of v10.2.1
