### ISSUE TITLE
addon services fail to start

### ISSUE THREAD

**Issue by arthurdent75** [hassio-addons/addon-base#205]
# Problem/Motivation

> the addon services fail to start when addon is installed from the GitHub repository

## Expected behavior

>  The addon services start when the addon is installed locally (from the _addon_ folder in samba share) or I run it as a standalone docker,

## Actual behavior

>   The addon services fail to start when the addon is installed from GitHub repository

![image](https://user-images.githubusercontent.com/60071192/207163297-e405430b-279f-4869-9be4-76c6ea03ab18.png)

## How to reproduce

> repository: https://github.com/arthurdent75/SimpleScheduler-BETA

**Comment by sinclairpaul** [comment]
Check the blog post at <https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images>

This isn't an issue with the image, so closing.
