### ISSUE TITLE
supervisor don't run

### ISSUE THREAD

**Issue by almirus** [hassio-addons/addon-base#210]
# Problem/Motivation

supervisor_run not started

## Expected behavior

running container with HA

## Actual behavior

error 
<pre>*  Executing task: supervisor_run 

zsh:1: permission denied: supervisor_run

 *  The terminal process "/usr/bin/zsh '-c', 'supervisor_run'" failed to launch (exit code: 126). 
 *  Press any key to close the terminal. </pre>
after run task "Start Home Assistant" 

## Steps to reproduce

create new dir (for test addon)
copy [file](https://raw.githubusercontent.com/home-assistant/addons-example/main/.devcontainer.json) to .devcontainer\devcontainer.json
copy [file](https://raw.githubusercontent.com/home-assistant/addons-example/main/.vscode/tasks.json) to .vscode\tasks.json
open dir in VS Code
start Task - Start Home Assistant

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

![image](https://user-images.githubusercontent.com/16898685/210804941-728e45d0-a328-4687-883b-a6c5f71d9838.png)

**Comment by frenck** [comment]
Those are instructions by the Home Assistant project and their containers/add-ons. This base image is not part of that. The community add-ons project uses a different structure and is not using dev containers.

../Frenck

**Comment by almirus** [comment]
@frenck hello! i try to do this https://developers.home-assistant.io/docs/add-ons/testing
