### ISSUE TITLE
build FROM armv7-base; RUN lines fail 

### ISSUE THREAD

**Issue by kentloving** [hassio-addons/addon-base#39]
# Problem/Motivation

I'm following instructions at https://developers.home-assistant.io/docs/hassio_addon_testing.   My HA is on a Raspberry Pi 3 B, so I'm using armv7 base, using this command:

docker build --build-arg BUILD_FROM="homeassistant/armv7-base:latest" -t local/my-test-addon .

## Expected behavior

a successful build. 

FWIW the the amd64 base works as expected. That is, change the BUILD_FROM argument to amd64-base:latest and I get a success

ful build.

## Actual behavior

For the RUN line in Dockerfile, there is this error:
standard_init_linux.go:211: exec user process caused "exec format error"
The command '/bin/ash -o pipefail -c chmod a+x /run.sh' returned a non-zero code: 1

## Steps to reproduce

1. Set up a build machine w/ Docker. Mine is Alpine standard 3.11.6 x86_64 running in Virtualbox on a Mac. 
2. Copy the config.json, Dockerfile, and run.sh from the "build your first addon" at https://developers.home-assistant.io/docs/hassio_addon_tutorial to the build machine
3. Run the docker build command stated above
The attached archive contains the 3 files plus a capture of stdout of the build command
[Archive.zip](https://github.com/hassio-addons/addon-base/files/4534856/Archive.zip)

## Proposed changes

I have no proposal

<blockquote><img src="https://developers.home-assistant.io/img/default-social.png" width="48" align="right"><div><strong><a href="https://developers.home-assistant.io/docs/hassio_addon_testing">Local add-on testing | Home Assistant Developer Docs</a></strong></div><div>The fastest way to develop add-ons is by adding them to your local add-on repository. To access your local add-on repository, install either the [Samba add-on] or [SSH add-on].</div></blockquote>
<blockquote><img src="https://developers.home-assistant.io/img/default-social.png" width="48" align="right"><div><strong><a href="https://developers.home-assistant.io/docs/hassio_addon_tutorial">Tutorial: Making your first add-on | Home Assistant Developer Docs</a></strong></div><div>So you've got Home Assistant going and you've been enjoying the built-in add-ons but you're missing this one application. Time to make your own add-on! In Supervisor 24 we introduced the option to have local add-ons be build on your device. This is great for developing new add-ons locally.</div></blockquote>

**Comment by frenck** [comment]
You can't run ARMv7 programs on an AMD64 based machine. This would need Qemu to achieve this.

There is a utility available that can help you with that:

<https://github.com/home-assistant/hassio-builder>
