### ISSUE TITLE
Building my own addon inside hassio fails on network access

### ISSUE THREAD

**Issue by buhl** [hassio-addons/addon-base#40]
When building my own addon inside hassio any RUN command in the Dockerfile which tries to get network access fails. I can build my addon outside hassio and either with portainer or dockerhub have hassio load and run it without problems.

We have a discussion on the problem here 
https://community.home-assistant.io/t/errors-when-buliding-a-new-addon/198841/11

<blockquote><img src="https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/b/a/bad3e5f9ad67c1ddf145107ce7032ac1d7b22563.svg" width="48" align="right"><div><img src="https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/optimized/3X/f/4/f42b82971fce994297fbc2b269efa248beef897b_2_32x32.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/errors-when-buliding-a-new-addon/198841/11">Errors when buliding a new addon</a></strong></div><div>I tried to do a curl that failed. So I am thinking that your first hunch was correct and there is simply no network where the images are built. I found a issue on github where @frenck mentions a docker image for building images under different architectures. So my thinking is as yours, that they are building the images outside of hassio. I think I will create an issue on github and link to this thread</div></blockquote>

**Comment by frenck** [comment]
Please share the build output. I cannot help you if you don't share other information. "It doesn't work" isn't something I can help with. Other resources, like a link to the sources you are trying to get working, would help as well.

**Comment by buhl** [comment]
Sorry about my briefness @frenck, i should have written a better text. We do have a longer discussion on the forum link.

Non of us know how to get the build log out of hassio

When the build fails we see lines like this

‘’’
20-05-24 11:00:15 ERROR (SyncWorker_3) [supervisor.docker.addon] Can’t build 13861ffc/amd64-addon-ozwcp:1.1.2: The command ‘/bin/ash -o pipefail -c apk update’ returned a non-zero code: 5
‘’’

In the system log. It seems that every time a command has to acces network it fails.

Even a simple curl
‘’’
RUN curl -h
RUN curl https://google.com/
‘’’
and I get the error:
‘’’
… [supervisor.docker.add-on] Can’t build local/amd64-addon-radicale:3.0.1: The command ‘/bin/ash -o pipefail -c curl https://google.com/’ returned a non-zero code: 6
‘’’

**Comment by frenck** [comment]
Please link the sources you are trying to build so I can have a look

**Comment by buhl** [comment]
I have tried both my own
https://github.com/buhl/hassons
and
https://github.com/jkeljo/hassio-addons
with same result. I used to be able to build jkeljo's addon

**Comment by sinclairpaul** [comment]
Builds here locally

![image](https://user-images.githubusercontent.com/24625998/83315220-66f66900-a1ec-11ea-9391-571c4fba69c3.png)

You mention that anything external fails?, can you SSH to your server and actually check DNS is functioning?

**Comment by buhl** [comment]
Aha! nice catch @sinclairpaul 
I only have ssh access to hassio through core_ssh in there dns works.
but I tried adding RUN https://8.8.8.8/ which worked and then RUN nslookup google.com
I can pull repositories and docker images so dns works to some extend in hassio.
Now that we narrowed it down to DNS problems during builds its probably worth mentioning that I use AdGuard Home (through an addon) as my DNS.

**Comment by frenck** [comment]
You probably missed step 1 of the AdGuard add-on documentation.

Closing this, as it is not an issue.

**Comment by buhl** [comment]
Hey @sinclairpaul and @frenck, thanks to both of you for take your time to help me. It was indeed my own fault and it is fixed now. 
Sorry for the inconvenience

**Comment by frenck** [comment]
Glad you've got it fixed! 👍
