### ISSUE TITLE
Unknown HTTP error occured on starting add-on

### ISSUE THREAD

**Issue by alex3305** [hassio-addons/addon-base#41]
# Problem/Motivation

I'm currently working on my [own add-ons](https://github.com/alex3305/hassio-addons), and that is going wonderfully. I'm glad with all the work the contributors have put into this project, so thanks for that. However when building my own add-ons I always get the following error in my logs, which I'm unable to fix.

```
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: Traefik
 Traefik is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy.
-----------------------------------------------------------
 Add-on version: 3.3.0
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[12:58:39] ERROR: Unknown HTTP error occured
 System:   (amd64 / qemux86-64)
 Home Assistant Core: 0.116.2
 Home Assistant Supervisor: 247
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
```

It doesn't matter whether or not it's a local add-on or not. It always seems to appear. Fortunately it doesn't affect the add-on's functionality. 

Running the `/etc/cont-init.d/00-banner.sh` within the add-ons container doesn't get me the same error:

```
-----------------------------------------------------------
 Add-on: Traefik
 Traefik is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy.
-----------------------------------------------------------
 Add-on version: 3.3.0
 You are running the latest version of this add-on.
 System:   (amd64 / qemux86-64)
 Home Assistant Core: 0.116.2
 Home Assistant Supervisor: 247
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
```

So I'm currently puzzled where and how I could solve this.

## Expected behavior

I expected that the output of the container and `00-banner.sh` to be the same. Both without an error.

## Actual behavior

An Unknown HTTP error shows up in the logging. 

## Steps to reproduce

Install one of my add-ons and run it. Or perhaps build a minimal add-on.

**Comment by sinclairpaul** [comment]
Please check the documentation for addon configuration at https://developers.home-assistant.io/docs/add-ons/configuration/

Hint - hassio_role/hassio_api

You should also be seeing an error/warning in the Supervisor log.

I would strongly suggest using Discord for questions around configuration.

**Comment by alex3305** [comment]
@sinclairpaul Thank you for your adequate response. Indeed adding `hassio_role` and `hassio_api` within the `config.json` fixed this as:

```json
{
    "hassio_role": "default",
    "hassio_api": true,
}
```

IMHO this was not really clear from either documentation and the security error in Supervisor log. I was also a bit puzzled because the call did work when called within the container itself.

Hopefully this issue can be a reference for future use. I will also keep Discord in mind for future questions. Thanks again!
