### ISSUE TITLE
Which base to use?

### ISSUE THREAD

**Issue by rchl** [hassio-addons/addon-base#84]
I'm just confused a bit because I see that none of the official addons at https://github.com/home-assistant/addons use this base image. I can see those being used there:

 - homeassistant/[arch]-base
 - homeassistant/[arch]-base-debian
 - homeassistant/[arch]-homeassistant-base
 - ...

So what is the recommended one to use for user-created addons? Those listed above or the one from this repo?

Also, what are the actual tags of images from this repo? I don't see those being listed anywhere or any links to docker hub.

So I guess the point of this issue is to clarify some things to me and ideally put that information in the readme.

**Comment by frenck** [comment]
The core add-ons do use the base images?

<https://github.com/home-assistant/addons/blob/master/zwave_js/build.json>
